// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OneCup.Infrastructure.Migrations
{
    /// <summary>
    /// 合并占位迁移：feat/color-mgmt 合入 main（含 customer + unit）时生成。
    ///
    /// Up/Down 为空——colors / customers / measurement_units 三张表
    /// 已分别由 AddColorModule / AddCustomerModule / AddUnitModule 创建。
    /// 本迁移的唯一作用是刷新 ModelSnapshot，使其反映 color+customer+unit
    /// 三模块合体后的完整模型（见并行开发约定 §4.4）。后续 migrations add
    /// 会基于这个一致的快照计算增量，不再重复建表。
    /// </summary>
    public partial class MergeColorWithMain : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 无操作：表已由各自模块迁移创建
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // 无操作：对应 Up 也无操作
        }
    }
}
