// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneCup.Infrastructure.Persistence;

#nullable disable

namespace OneCup.Infrastructure.Migrations
{
    [DbContext(typeof(OneCupDbContext))]
    [Migration("20260704170238_AddMaterialModule")]
    partial class AddMaterialModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneCup.Domain.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("ColorFamily")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color_family");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .HasColumnName("hex")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_zh");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("remark");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_colors_code");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("short_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.LoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Message")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("message");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_login_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_logs_user_id");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_login_logs_username");

                    b.ToTable("login_logs", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("remark");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("spec");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_materials_code");

                    b.HasIndex("UnitId");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("factor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_zh");

                    b.Property<int>("Precision")
                        .HasColumnType("integer")
                        .HasColumnName("precision");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("symbol");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_measurement_units_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_measurement_units_code");

                    b.ToTable("measurement_units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010001"),
                            Category = "LENGTH",
                            Code = "meter",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = true,
                            NameEn = "Meter",
                            NameZh = "米",
                            Precision = 2,
                            SortOrder = 1,
                            Symbol = "m"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010002"),
                            Category = "LENGTH",
                            Code = "decimeter",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.1m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Decimeter",
                            NameZh = "分米",
                            Precision = 2,
                            SortOrder = 2,
                            Symbol = "dm"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010003"),
                            Category = "LENGTH",
                            Code = "centimeter",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.01m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Centimeter",
                            NameZh = "厘米",
                            Precision = 2,
                            SortOrder = 3,
                            Symbol = "cm"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010004"),
                            Category = "LENGTH",
                            Code = "yard",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.9144m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Yard",
                            NameZh = "码",
                            Precision = 2,
                            SortOrder = 4,
                            Symbol = "yd"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010005"),
                            Category = "LENGTH",
                            Code = "foot",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.3048m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Foot",
                            NameZh = "英尺",
                            Precision = 2,
                            SortOrder = 5,
                            Symbol = "ft"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010010"),
                            Category = "WEIGHT",
                            Code = "kilogram",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = true,
                            NameEn = "Kilogram",
                            NameZh = "千克",
                            Precision = 2,
                            SortOrder = 1,
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010011"),
                            Category = "WEIGHT",
                            Code = "gram",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.001m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Gram",
                            NameZh = "克",
                            Precision = 2,
                            SortOrder = 2,
                            Symbol = "g"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010012"),
                            Category = "WEIGHT",
                            Code = "ton",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1000m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Ton",
                            NameZh = "吨",
                            Precision = 2,
                            SortOrder = 3,
                            Symbol = "t"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010013"),
                            Category = "WEIGHT",
                            Code = "pound",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.453592m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Pound",
                            NameZh = "磅",
                            Precision = 2,
                            SortOrder = 4,
                            Symbol = "lb"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010020"),
                            Category = "AREA",
                            Code = "square_meter",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = true,
                            NameEn = "Square Meter",
                            NameZh = "平方米",
                            Precision = 2,
                            SortOrder = 1,
                            Symbol = "㎡"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010021"),
                            Category = "AREA",
                            Code = "square_yard",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.836127m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Square Yard",
                            NameZh = "平方码",
                            Precision = 2,
                            SortOrder = 2,
                            Symbol = "yd²"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010030"),
                            Category = "COUNT",
                            Code = "piece",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = true,
                            NameEn = "Piece",
                            NameZh = "件",
                            Precision = 0,
                            SortOrder = 1,
                            Symbol = "件"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010031"),
                            Category = "COUNT",
                            Code = "roll",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Roll",
                            NameZh = "卷",
                            Precision = 0,
                            SortOrder = 2,
                            Symbol = "卷"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010032"),
                            Category = "COUNT",
                            Code = "bolt",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Bolt",
                            NameZh = "匹",
                            Precision = 0,
                            SortOrder = 3,
                            Symbol = "匹"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010033"),
                            Category = "COUNT",
                            Code = "set",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Set",
                            NameZh = "套",
                            Precision = 0,
                            SortOrder = 4,
                            Symbol = "套"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010040"),
                            Category = "VOLUME",
                            Code = "liter",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = true,
                            NameEn = "Liter",
                            NameZh = "升",
                            Precision = 2,
                            SortOrder = 1,
                            Symbol = "L"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010041"),
                            Category = "VOLUME",
                            Code = "milliliter",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 0.001m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Milliliter",
                            NameZh = "毫升",
                            Precision = 2,
                            SortOrder = 2,
                            Symbol = "mL"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010050"),
                            Category = "YARN",
                            Code = "tex",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 1m,
                            IsActive = true,
                            IsBase = true,
                            NameEn = "Tex",
                            NameZh = "特",
                            Precision = 2,
                            SortOrder = 1,
                            Symbol = "tex"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010051"),
                            Category = "YARN",
                            Code = "dtex",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 10m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Decitex",
                            NameZh = "分特",
                            Precision = 2,
                            SortOrder = 2,
                            Symbol = "dtex"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000010052"),
                            Category = "YARN",
                            Code = "denier",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Factor = 9m,
                            IsActive = true,
                            IsBase = false,
                            NameEn = "Denier",
                            NameZh = "旦尼尔",
                            Precision = 2,
                            SortOrder = 3,
                            Symbol = "D"
                        });
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_zh");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("TargetTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TargetTypeCode")
                        .HasDatabaseName("ix_numbering_categories_target_type");

                    b.HasIndex("TargetTypeCode", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_numbering_categories_type_code");

                    b.ToTable("numbering_categories", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("")
                        .HasColumnName("category_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentSeq")
                        .HasColumnType("integer")
                        .HasColumnName("current_seq");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("")
                        .HasColumnName("period_key");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "CategoryCode", "PeriodKey")
                        .IsUnique()
                        .HasDatabaseName("ux_numbering_counters_bucket");

                    b.ToTable("numbering_counters", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeneratedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("generated_code");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<int>("SeqValue")
                        .HasColumnType("integer")
                        .HasColumnName("seq_value");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedCode")
                        .HasDatabaseName("ix_numbering_logs_code");

                    b.HasIndex("RuleId", "CreatedAt")
                        .HasDatabaseName("ix_numbering_logs_rule_id");

                    b.HasIndex("TargetType", "CreatedAt")
                        .HasDatabaseName("ix_numbering_logs_target_type");

                    b.ToTable("numbering_logs", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DateSegment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("date_segment");

                    b.Property<bool>("IncludeCategory")
                        .HasColumnType("boolean")
                        .HasColumnName("include_category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefix");

                    b.Property<string>("Remark")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("remark");

                    b.Property<string>("ResetPeriod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reset_period");

                    b.Property<string>("Separator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("separator");

                    b.Property<short>("SeqLength")
                        .HasColumnType("smallint")
                        .HasColumnName("seq_length");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TargetType")
                        .HasDatabaseName("ix_numbering_rules_target_type");

                    b.HasIndex("TargetType", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_numbering_rules_target_type_active")
                        .HasFilter("\"is_active\" = true");

                    b.ToTable("numbering_rules", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingTargetType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameZh")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_zh");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_numbering_target_types_code");

                    b.ToTable("numbering_target_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000201"),
                            Code = "fabric",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NameEn = "Fabric",
                            NameZh = "面料",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000202"),
                            Code = "material",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NameEn = "Material",
                            NameZh = "原料",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000203"),
                            Code = "equipment",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NameEn = "Equipment",
                            NameZh = "设备",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000204"),
                            Code = "customer",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NameEn = "Customer",
                            NameZh = "客户",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000205"),
                            Code = "color",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NameEn = "Color",
                            NameZh = "颜色",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000206"),
                            Code = "product",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NameEn = "Product",
                            NameZh = "产品",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("OneCup.Domain.Entities.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("http_method");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("module");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("request_path");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_payload");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("result");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_name");

                    b.Property<string>("TargetType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("target_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_op_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_op_logs_user_id");

                    b.HasIndex("Module", "Action")
                        .HasDatabaseName("ix_op_logs_module_action");

                    b.ToTable("operation_logs", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000301"),
                            Code = "fabric:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看面料开发"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000302"),
                            Code = "fabric:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "录入面料开发"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000303"),
                            Code = "fabric:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑面料开发"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000304"),
                            Code = "fabric:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除面料开发"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000305"),
                            Code = "material:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看原料物料"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000306"),
                            Code = "material:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "录入原料物料"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000307"),
                            Code = "material:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑原料物料"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000308"),
                            Code = "material:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除原料物料"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000309"),
                            Code = "equipment:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看设备"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030a"),
                            Code = "equipment:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "录入设备"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030b"),
                            Code = "equipment:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑设备"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030c"),
                            Code = "equipment:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除设备"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030d"),
                            Code = "customer:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看客户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030e"),
                            Code = "customer:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "录入客户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000030f"),
                            Code = "customer:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑客户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000310"),
                            Code = "customer:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除客户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000311"),
                            Code = "color:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看颜色对色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000312"),
                            Code = "color:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "录入颜色对色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000313"),
                            Code = "color:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑颜色对色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000314"),
                            Code = "color:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除颜色对色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000315"),
                            Code = "product:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看产品"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000316"),
                            Code = "product:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "录入产品"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000317"),
                            Code = "product:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑产品"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000318"),
                            Code = "product:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除产品"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000319"),
                            Code = "system:user:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看用户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000031a"),
                            Code = "system:user:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增用户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000031b"),
                            Code = "system:user:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑用户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000031c"),
                            Code = "system:user:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除用户"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000031d"),
                            Code = "system:user:reset-password",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "重置用户密码"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000031e"),
                            Code = "system:role:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看角色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000031f"),
                            Code = "system:role:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增角色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000320"),
                            Code = "system:role:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑角色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000321"),
                            Code = "system:role:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除角色"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000322"),
                            Code = "system:numbering:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看编号管理"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000323"),
                            Code = "system:numbering:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增编号规则"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000324"),
                            Code = "system:numbering:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑编号规则"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000325"),
                            Code = "system:numbering:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除编号规则"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000326"),
                            Code = "system:unit:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看计量单位"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000327"),
                            Code = "system:unit:create",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增计量单位"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000328"),
                            Code = "system:unit:update",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑计量单位"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000329"),
                            Code = "system:unit:delete",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除计量单位"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-00000000032a"),
                            Code = "system:audit:read",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查看审计日志"
                        });
                });

            modelBuilder.Entity("OneCup.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "admin",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "系统超级管理员，拥有全部权限",
                            Name = "管理员"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Code = "developer",
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "面料开发相关权限",
                            Name = "开发员"
                        });
                });

            modelBuilder.Entity("OneCup.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "管理员",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "$2a$12$Q.gT.FJroDeCmWFH6dHJcOdjxPIQgST/nEYCECypvJsLxj5wDQoSi",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("permission_id")
                        .HasColumnType("uuid");

                    b.HasKey("role_id", "permission_id");

                    b.HasIndex("permission_id");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000301")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000302")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000303")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000304")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000305")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000309")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-00000000030d")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000311")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-000000000315")
                        },
                        new
                        {
                            role_id = new Guid("00000000-0000-0000-0000-000000000003"),
                            permission_id = new Guid("00000000-0000-0000-0000-00000000032a")
                        });
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("user_roles");

                    b.HasData(
                        new
                        {
                            user_id = new Guid("00000000-0000-0000-0000-000000000001"),
                            role_id = new Guid("00000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("OneCup.Domain.Entities.Material", b =>
                {
                    b.HasOne("OneCup.Domain.Entities.MeasurementUnit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingCounter", b =>
                {
                    b.HasOne("OneCup.Domain.Entities.NumberingRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("OneCup.Domain.Entities.NumberingLog", b =>
                {
                    b.HasOne("OneCup.Domain.Entities.NumberingRule", "Rule")
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("OneCup.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("OneCup.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.HasOne("OneCup.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneCup.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("OneCup.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneCup.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneCup.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
